# Home page
GET http://{{host}}:{{port}}

###
# Get all engineers
GET http://{{host}}:{{port}}/engineer

###
# Get engineer by ID (Barbara Liskov)
GET http://{{host}}:{{port}}/engineer/1

###
# Create engineer
PUT http://{{host}}:{{port}}/engineer
Content-Type: application/json

{
  "FirstName": "Rob",
  "LastName": "Pike"
}

###
# Delete engineer
DELETE http://{{host}}:{{port}}/engineer/6
Content-Type: application/json

###
