version: '3.4'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'go_crud'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "8080:8080"